### PR TITLE
feat: Add prop to support custom snap gap renderer

### PR DESCRIPTION
**Pull request by nelsondude**

### CODE REVIEW

**Comment by daybrush** [comment]
@nelsondude 

What content do you want to insert on the guideline?

**Comment by nelsondude** [comment]
Specifically, I need the gap guidelines to look like 
Screen Shot 2020-12-30 at 11 56 26 AM. So the best way to do this is probably to just let the user customize the render function by providing their own

**Comment by daybrush** [comment]
@nelsondude 

Thank you for asking for PR. But the custom range is too much.

**Comment by daybrush** [comment]
@nelsondude 

use snapDistFormat prop

**Comment by nelsondude** [comment]
snapDistFormat takes a number and only affects rendering of the distance. I need to add the extra UI elements / arrows like in the picture I posted above by returning some JSX. What is the problem with allowing a custom rendering function? I think this makes it much more customizable if the user needs

**Comment by daybrush** [comment]
@nelsondude 

I'm sorry. It contains many parameters. It is also a specification that can be changed at any time.

**Pull request closed without merging**
